[DEFAULT]
# target model id
MODEL_ID = gemma-4-31b-it
# vLLM endpoint (openai compatible)
# API_URL = http://hai-server:8000/v1/chat/completions
API_URL = http://hai-server:8000/v1/chat/completions
NUM_CTX = 262144
REQ_TIMEOUT = 300